# Generated by Django 2.1.3 on 2018-11-11 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=30)),
                ('user_icon_url', models.URLField()),
                ('user_bio', models.CharField(max_length=100)),
                ('user_dictionaly', models.CharField(max_length=200)),
            ],
        ),
    ]
